defaults:
  - _self_
  - config: unet

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}

config:
  data_path: '/home/cdy/General-Medical-Image-Segmentation-CNN-Framework/PCA22/source/train'
  gt_path: '/home/cdy/General-Medical-Image-Segmentation-CNN-Framework/PCA22/label/train'
  pred_data_path: '/home/cdy/General-Medical-Image-Segmentation-CNN-Framework/PCA22/source/test'
  pred_gt_path: '/home/cdy/General-Medical-Image-Segmentation-CNN-Framework/PCA22/label/test'
  init_type: 'xavier'  # ['normal', 'xavier', 'xavier_uniform', 'kaiming', 'orthogonal', 'none]
  aug: False  # True or False
  epochs: 100
  epochs_per_checkpoint: 25
  batch_size: 4
  init_lr: 0.01
  scheduler_step_size: 20
  scheduler_gamma: 0.8
  cudnn_enabled: True
  cudnn_benchmark: True
  use_scheduler: True
  gpu: '1'
  
  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}